### ISSUE TITLE
Can not connect to MyLv

### ISSUE THREAD

**Issue by shinmen** [Linkvalue-Interne/LvConnect#4]
When I try to connect to MyLV, I can enter my credentials but cannot access MyLV app.
The response I get from 'https://mylv.link-value.fr/api/auth'
`{"statusCode":401,"error":"Unauthorized","message":"invalid_grant"}`

![capture du 2019-02-20 09-06-18](https://user-images.githubusercontent.com/4790740/53079644-27c06f00-34f7-11e9-8f18-e242fc3da263.png)

**Comment by Oliboy50** [comment]
MyLV isn't supported anymore

@shinmen I suggest to 🙈 on this issue right now and 🙏 for a better future

(feel free to reopen or make a new issue if the issue persist)
